# License: CC0-1.0
# This is an example organization configuration file.
#
# How to use it:
# 1. Set an enviroment variable called ORG_NAME
# 2. Make a copy of this file and rename it to <ORG_NAME>.yml – this will be your
#   default settings file. You can also create <ORG_NAME>.enviroment.yml which
#   will overwrite your settings on per enviroment basis.
# 3. Set your details in the new files et voila!

mailer:
  default_from: Default Org Team <hi@defaultorg.com>"
  delivery_method: "smtp"
  address: "localhost"
  port: 1025
  host: "localhost:5000"
  email: 'email@email.org'

devise:
  mailer_sender: "hi@defaultorg.com"

intntl:
  currencies: ["eur"]
  eur:
    unit: "euro"
    subunit: "cents"
    symbol: "€"
    abbv: "eur"
    format: "%n%u"

nonprofit_regions: [ 'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'PR', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY' ]